CXX      = g++
CXXFLAGS = -Ofast -pthread -std=c++11 -Wall -Werror -pedantic-errors -fmessage-length=0

moons1:
	$(CXX) $(CXXFLAGS) moons.cpp -o moons.out
moons2:
	$(CXX) $(CXXFLAGS) moons2.cpp -o moons2.out
clean:
	rm -f *.out *.exe
