CXX      = g++
CXXFLAGS = -Ofast -pthread -std=c++11 -Wall -Werror -pedantic-errors -fmessage-length=0

fuel1:
	$(CXX) $(CXXFLAGS) fuel1.cpp -o fuel1.out
fuel2:
	$(CXX) $(CXXFLAGS) fuel2.cpp -o fuel2.out
clean:
	rm -f fuel1.out fuel1.exe fuel2.out fuel2.exe
